[Config]
# App ID
api_id = 2040
# App Hash
api_hash = b18441a1ff607e10a989891a5462e627
# Bot token
token="token" 
# Chat or user id that the bot will relay to
destinationID=youruserid 
# Command prefix
commandPrefix="$"

[Strings]
# Your username
name="yourname"
